/*!CK:3103603105!*//*1385348276,173198911*/

if (self.CavalryLogger) { CavalryLogger.start_js(["HKmIh"]); }

__d("PopoverMenuContextMinWidth",["CSS","Style","copyProperties","cx","shield"],function(a,b,c,d,e,f){var g=b('CSS'),h=b('Style'),i=b('copyProperties'),j=b('cx'),k=b('shield');function l(m){"use strict";this._popoverMenu=m;this._popover=m.getPopover();}l.prototype.enable=function(){"use strict";this._setMenuSubscription=this._popoverMenu.subscribe('setMenu',k(this._onSetMenu,this));};l.prototype.disable=function(){"use strict";this._setMenuSubscription.unsubscribe();this._setMenuSubscription=null;if(this._showSubscription){this._showSubscription.unsubscribe();this._showSubscription=null;}if(this._menuSubscription){this._menuSubscription.unsubscribe();this._menuSubscription=null;}};l.prototype._onSetMenu=function(){"use strict";this._menu=this._popoverMenu.getMenu();this._showSubscription=this._popover.subscribe('show',k(this._updateWidth,this));var m=this._updateWidth.bind(this);this._menuSubscription=this._menu.subscribe(['change','resize'],function(){setTimeout(m,0);});this._updateWidth();};l.prototype._updateWidth=function(){"use strict";var m=this._menu.getRoot(),n=this._popoverMenu.getTriggerElem(),o=n.offsetWidth;h.set(m,'min-width',o+'px');g.conditionClass(m,"_575s",o>=m.offsetWidth);};i(l.prototype,{_setMenuSubscription:null,_showSubscription:null,_menuSubscription:null});e.exports=l;});
__d("TimelineEditProfileDialogButton",["Event","Arbiter"],function(a,b,c,d,e,f){var g=b('Event'),h=b('Arbiter'),i,j={init:function(k,l){g.listen(k,'click',function(){j.hideDialog();if(l)h.inform('timeline_edit_'+l);});},registerDialog:function(k){i=k;},hideDialog:function(){if(i){i.hide();i=null;}}};e.exports=j;});
__d("Selector-PUSHSAFE",["ArbiterMixin","BehaviorsMixin","Button","DOM","DOMQuery","csx","mixin"],function(a,b,c,d,e,f){var g=b('ArbiterMixin'),h=b('BehaviorsMixin'),i=b('Button'),j=b('DOM'),k=b('DOMQuery'),l=b('csx'),m=b('mixin'),n=m(g,h);for(var o in n)if(n.hasOwnProperty(o))q[o]=n[o];var p=n===null?null:n.prototype;q.prototype=Object.create(p);q.prototype.constructor=q;q.__superConstructor__=n;function q(r,s,t,u,v){"use strict";this._popoverMenu=r;this._button=s;this._menu=t;this._input=u;this.init();v.behaviors&&this.enableBehaviors(v.behaviors);}q.prototype.init=function(){"use strict";this._menu.subscribe('change',function(r,s){this._setLabelContent(s.label);this._input.value=s.value;this.inform('change',s);}.bind(this));this._popoverMenu.getPopover().subscribe(['hide','show'],function(r){this.inform(r);}.bind(this));};q.prototype._setLabelContent=function(r){"use strict";var s=k.find(this._button,"span._55pe");j.setContent(s,r);};q.prototype.setValue=function(r){"use strict";this._menu.setValue(r);};q.prototype.getValue=function(){"use strict";return this._input.value;};q.prototype.getName=function(){"use strict";return this._input.name;};q.prototype.getButton=function(){"use strict";return this._button;};q.prototype.getMenu=function(){"use strict";return this._menu;};q.prototype.enable=function(){"use strict";i.setEnabled(this._button,true);this._popoverMenu.enable();};q.prototype.disable=function(){"use strict";i.setEnabled(this._button,false);this._popoverMenu.disable();};e.exports=q;});
__d("legacy:LegacyContextualDialog",["LegacyContextualDialog"],function(a,b,c,d){a.LegacyContextualDialog=b('LegacyContextualDialog');},3);
__d("legacy:LayerDestroyOnHide",["LayerDestroyOnHide"],function(a,b,c,d){a.LayerDestroyOnHide=b('LayerDestroyOnHide');},3);
__d("legacy:LayerHideOnBlur",["LayerHideOnBlur"],function(a,b,c,d){a.LayerHideOnBlur=b('LayerHideOnBlur');},3);